ci:
  skip: [export-requirements, hadolint-docker]
  autofix_commit_msg: 'refactor: `pre-commit.ci` auto fix'
  autofix_prs: true
  autoupdate_commit_msg: 'ci: `pre-commit.ci` auto update'

repos:
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/life4/flakehell
    rev: v.0.8.0
    hooks:
    - id: flakehell
      exclude: ^docs|tests
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    - id: mypy
      files: ^src
      additional_dependencies: [types-all]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.28.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint
        stages: [commit-msg]
        args: [--ignore=B6, --msg-filename]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.5
    hooks:
      - id: vulture
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 0.5.2
    hooks:
      - id: tox-ini-fmt
  - repo: local
    hooks:
      - id: export-requirements
        name: export-requirements
        language: system
        pass_filenames: false
        entry: poetry export --without-hashes -o requirements.txt
        files: ^(pyproject.toml|poetry.lock)$
  - repo: https://github.com/hadolint/hadolint
    rev: v2.10.0
    hooks:
      - id: hadolint-docker
        args: ['--ignore', 'DL3006']
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
