site_name: Dotify Cli
site_description: "Download metadata rich music from Spotify"
site_url: "https://billsioros.github.io/dotify-cli/"
repo_url: "https://github.com/billsioros/dotify-cli"
edit_uri: "edit/master/docs/"
repo_name: "billsioros/dotify-cli"
copyright: |
  Copyright &copy; 2021-2021 <a href="https://github.com/billsioros" target="_blank" rel="noopener">Vasilis Sioros</a>

nav:
  - Overview: index.md
  - Code Reference:
    - Dotify Cli: src/dotify_cli.md
  - Contributing:
    - Contributing Guidelines: CONTRIBUTING.md
    - Code Of Conduct: CODE_OF_CONDUCT.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: false
- minify:
    minify_html: true

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: "¤"
- mdx_truly_sane_lists

extra:
  version:
    provider: mike
