name: CI

on:
  push:
    branches: [master]
    paths:
      - 'dotify_cli/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'
  pull_request:
    branches: [master]
    paths:
      - 'dotify_cli/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  tox:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
        exclude:
          - platform: windows-latest
            python-version: 3.8
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.3
        with:
          poetry-version: 1.1.8

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            .tox
            .venv
          key: ${{ matrix.platform }}-tox-venv-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Test with tox
        run: poetry run python -m tox
